language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean install
  - ./mvnw test

notifications:
  email:
    recipients:
      - a.canal.2016@alumnos.urjc.es
    on_success: always
    on_failure: always
